replicaCount: 1

image:
  repository: ghcr.io/solomcc/my-go-api:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083
  targetPort: 8080

ingress:
  enabled: true
  host: go.local